Models/Paqueterias.cs
using System.ComponentModel.DataAnnotations;

namespace TodoParaTuPerro.Models
{
    public class Paqueterias
    {
        [Key]
        public int IdPaqueteria { get; set; }
        [Required]
        public string NombrePaqueteria { get; set; }
        [Required]
        public string Direccion { get; set; }
        [Required]
        public decimal CostoEnvio { get; set; }
        [Required]
        public string TiempoEntrega { get; set; }
    }
}

Models/Pedidos.cs
using System.ComponentModel.DataAnnotations;

namespace TodoParaTuPerro.Models
{
    public class Pedidos
    {
        [Key]
        public int IdPedido { get; set; }
        [Required]
        public string FechaPedido { get; set; }
        [Required]
        public int ProductoId { get; set; }
        [Required]
        public decimal Subtotal { get; set; }
        [Required]
        public decimal Total { get; set; }
        public string? NoGuia { get; set; }
        public string? Paqueteria { get; set; }
        public string? FechaEnvio { get; set; }
        public string? FechaEntrega { get; set; }
    }
}

Controllers/PaqueteriaControllers/PaqueteriaController.cs
using Microsoft.AspNetCore.Mvc;
using TodoParaTuPerro.Controllers.Datos;
using TodoParaTuPerro.Models;

namespace TodoParaTuPerro.Controllers.PaqueteriaControllers
{
    public class PaqueteriaController : Controller
    {
        private readonly ApplicationDbContext _db;
        public PaqueteriaController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Pedidos()
        {
            var listaPedidos = _db.Pedidos.Where(pedidos => pedidos.NoGuia == null || pedidos.Paqueteria == null || pedidos.FechaEnvio == null).ToList();
            var listaPaqueterias = _db.Paqueterias.ToList();
            var modelo = new PedidosPaqueteriaModel
            {
                ListaPedidos = listaPedidos,
                ListaPaqueterias = listaPaqueterias
            };
            
            return View(modelo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ActualizarGuia(Pedidos pedidos)
        {
            if (ModelState.IsValid)
            {
                var pedidoExistente = _db.Pedidos.Find(pedidos.IdPedido);

                if (pedidoExistente != null)
                {
                    pedidoExistente.NoGuia = pedidos.NoGuia;
                    pedidoExistente.Paqueteria = pedidos.Paqueteria;
                    pedidoExistente.FechaEnvio = pedidos.FechaEnvio;
                    _db.Pedidos.Update(pedidoExistente);
                    _db.SaveChanges();
                }
            }
            return RedirectToAction(nameof(Pedidos));
        }

        public IActionResult ActualizarEntrega(Pedidos pedidos)
        {
            if (ModelState.IsValid)
            {
                var pedidoExistente = _db.Pedidos.Find(pedidos.IdPedido);

                if (pedidoExistente != null)
                {
                    pedidoExistente.FechaEntrega = pedidos.FechaEntrega;
                    _db.Pedidos.Update(pedidoExistente);
                    _db.SaveChanges();
                }
            }
            return RedirectToAction(nameof(PedidosEnviados));
        }

        public IActionResult PedidosEnviados()
        {
            var lista = _db.Pedidos.Where(pedidos => pedidos.FechaEntrega == null && pedidos.NoGuia != null).ToList();
            return View(lista);
        }

        public IActionResult PedidosCompletados()
        {
            var lista = _db.Pedidos.Where(pedidos => pedidos.FechaEntrega != null && pedidos.NoGuia != null).ToList();
            return View(lista);
        }

        public IActionResult Paqueterias()
        {
            var lista = _db.Paqueterias.ToList();
            return View(lista);
        }

        public IActionResult CrearPaqueteria(Paqueterias paqueterias)
        {
            if (ModelState.IsValid)
            {
                _db.Paqueterias.Add(paqueterias);
                _db.SaveChanges();
            }
            return RedirectToAction(nameof(Paqueterias));
        }

        public IActionResult ActualizarPaqueteria(Paqueterias paqueterias)
        {
            if (ModelState.IsValid)
            {
                var paqueteriaExistente = _db.Paqueterias.Find(paqueterias.IdPaqueteria);

                if (paqueteriaExistente != null)
                {
                    paqueteriaExistente.NombrePaqueteria = paqueterias.NombrePaqueteria;
                    paqueteriaExistente.Direccion = paqueterias.Direccion;
                    paqueteriaExistente.CostoEnvio = paqueterias.CostoEnvio;
                    paqueteriaExistente.TiempoEntrega = paqueterias.TiempoEntrega;
                    _db.Paqueterias.Update(paqueteriaExistente);
                    _db.SaveChanges();
                }
            }
            return RedirectToAction(nameof(Paqueterias));
        }

        public IActionResult EliminarPaqueteria(Paqueterias paqueterias)
        {

            var paqueteriaExistente = _db.Paqueterias.Find(paqueterias.IdPaqueteria);
            if (paqueteriaExistente != null)
            {
                _db.Paqueterias.Remove(paqueteriaExistente);
                _db.SaveChanges();
            }
            return RedirectToAction(nameof(Paqueterias));
        }
    }
}

Views/Paqueteria/Paqueterias.cshtml
@model List<TodoParaTuPerro.Models.Paqueterias>;

@{
    ViewData["Title"] = "Paqueterias";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="Pedidos">
                <i class="bi bi-grid"></i>
                <span>Pedidos sin enviar</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="PedidosEnviados">
                <i class="bi bi-grid"></i>
                <span>Pedidos enviados</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="PedidosCompletados">
                <i class="bi bi-grid"></i>
                <span>Pedidos completados</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="Paqueterias">
                <i class="bi bi-grid"></i>
                <span>Paqueterías</span>
            </a>
        </li>
    </ul>
</aside>
<main id="main" class="main">
    <div class="container">
        <h1 class="text-center mt-4">Administración de Paqueterías</h1>
        <button class="btn btn-primary mt-4 mb-3" data-bs-toggle="modal" data-bs-target="#agregarModal">Agregar Paquetería</button>
        <table class="table table-striped mt-4">
            <thead>
                <tr>
                    <th scope="col">Nombre de la paquetería</th>
                    <th scope="col">Dirección</th>
                    <th scope="col">Costo de envío</th>
                    <th scope="col">Tiempo de entrega</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var paqueteria in Model)
                {
                    <tr>
                        <td>@paqueteria.NombrePaqueteria</td>
                        <td>@paqueteria.Direccion</td>
                        <td>@paqueteria.CostoEnvio</td>
                        <td>@paqueteria.TiempoEntrega</td>
                        <td>
                            <button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#editarModal"
                                    data-id="@paqueteria.IdPaqueteria" data-nombre="@paqueteria.NombrePaqueteria" data-direccion="@paqueteria.Direccion"
                                    data-costo="@paqueteria.CostoEnvio" data-tiempoEntrega="@paqueteria.TiempoEntrega" onclick="abrirModalEditar(this)">
                                Editar
                            </button>
                            <button class="btn btn-danger btn-sm" data-bs-toggle="modal"
                                    data-bs-target="#eliminarModal" data-id="@paqueteria.IdPaqueteria" onclick="abrirModalEliminar(this)">
                                Eliminar
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <!-- Modal para agregar -->
        <div class="modal fade" id="agregarModal" tabindex="-1" aria-labelledby="agregarModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="agregarModalLabel">Agregar Paquetería</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" asp-action="CrearPaqueteria">
                            <div class="mb-3">
                                <label for="nombreInput" class="form-label">Nombre de la paquetería</label>
                                <input type="text" class="form-control" id="nombreInputAgregar" name="NombrePaqueteria">
                            </div>
                            <div class="mb-3">
                                <label for="direccionInput" class="form-label">Dirección</label>
                                <input type="text" class="form-control" id="direccionInputAgregar" name="Direccion">
                            </div>
                            <div class="mb-3">
                                <label for="costoInput" class="form-label">Costo de envío</label>
                                <input type="number" class="form-control" id="costoInputAgregar" name="CostoEnvio" step="any">
                            </div>
                            <div class="mb-3">
                                <label for="tiempoInput" class="form-label">Tiempo de entrega</label>
                                <input type="text" class="form-control" id="tiempoInputAgregar" name="TiempoEntrega">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-primary">Agregar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal para editar -->
        <div class="modal fade" id="editarModal" tabindex="-1" aria-labelledby="editarModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editarModalLabel">Editar Paquetería</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" asp-action="ActualizarPaqueteria">
                            <input type="number" id="idInput" name="IdPaqueteria" hidden />
                            <div class="mb-3">
                                <label for="nombreInput" class="form-label">Nombre de la paquetería</label>
                                <input type="text" class="form-control" id="nombreInput" name="NombrePaqueteria">
                            </div>
                            <div class="mb-3">
                                <label for="direccionInput" class="form-label">Dirección</label>
                                <input type="text" class="form-control" id="direccionInput" name="Direccion">
                            </div>
                            <div class="mb-3">
                                <label for="costoInput" class="form-label">Costo de envío</label>
                                <input type="number" class="form-control" id="costoInput" name="CostoEnvio" step="any">
                            </div>
                            <div class="mb-3">
                                <label for="tiempoInput" class="form-label">Tiempo de entrega</label>
                                <input type="text" class="form-control" id="tiempoInput" name="TiempoEntrega">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-primary">Guardar cambios</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal para eliminar -->
        <div class="modal fade" id="eliminarModal" tabindex="-1" aria-labelledby="eliminarModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="eliminarModalLabel">Eliminar Paquetería</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>¿Estás seguro de que deseas eliminar esta paquetería?</p>
                    </div>
                    <form method="post" asp-action="EliminarPaqueteria">
                        <div class="modal-footer">
                            <input id="idInputEliminar" name="IdPaqueteria" hidden/>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</main>

<script>
    function abrirModalEditar(btnEditar) {
        var id = btnEditar.getAttribute("data-id");
        var nombre = btnEditar.getAttribute("data-nombre");
        var direccion = btnEditar.getAttribute("data-direccion");
        var costo = btnEditar.getAttribute("data-costo");
        var entrega = btnEditar.getAttribute("data-tiempoEntrega");

        document.getElementById("idInput").value = id;
        document.getElementById("nombreInput").value = nombre;
        document.getElementById("direccionInput").value = direccion;
        document.getElementById("costoInput").value = costo;
        document.getElementById("tiempoInput").value = entrega;
    }

    function abrirModalEliminar(btnEliminar){
        var id = btnEliminar.getAttribute("data-id");
        document.getElementById("idInputEliminar").value = id;
    }
</script>

Views/Paqueteria/Pedidos.cshtml
@using TodoParaTuPerro.Models;
@model TodoParaTuPerro.Models.PedidosPaqueteriaModel;

@{
    ViewData["Title"] = "Pedidos";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="Pedidos">
                <i class="bi bi-grid"></i>
                <span>Pedidos sin enviar</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="PedidosEnviados">
                <i class="bi bi-grid"></i>
                <span>Pedidos enviados</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="PedidosCompletados">
                <i class="bi bi-grid"></i>
                <span>Pedidos completados</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="Paqueterias">
                <i class="bi bi-grid"></i>
                <span>Paqueterías</span>
            </a>
        </li>
    </ul>
</aside>
<main id="main" class="main">
    <div class="container">
        <h1 class="text-center mt-4">Pedidos no enviados</h1>
        <table class="table table-striped mt-4">
            <thead>
                <tr>
                    <th scope="col">No. de pedido</th>
                    <th scope="col">Fecha del pedido</th>
                    <th scope="col">No. de guía</th>
                    <th scope="col">Paquetería</th>
                    <th scope="col">Fecha de envío</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pedido in Model.ListaPedidos)
                {
                    <tr>
                        <td>@pedido.IdPedido</td>
                        <td>@pedido.FechaPedido</td>
                        <td>@pedido.NoGuia</td>
                        <td>@pedido.Paqueteria</td>
                        <td>@pedido.FechaEnvio</td>
                        <td>
                            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editarModal"
                                    data-id="@pedido.IdPedido" data-fecha="@pedido.FechaPedido" data-guia="@pedido.NoGuia" onclick="abrirModalEditar(this)">
                                Editar
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <!-- Modal -->
        <div class="modal fade" id="editarModal" tabindex="-1" aria-labelledby="editarModalLabel" aria-hidden="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editarModalLabel">Editar Información</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" asp-action="ActualizarGuia">
                            <div class="mb-3">
                                <label for="pedidoId" class="form-label">No. de pedido:</label>
                                <input id="pedidoId" name="IdPedido" hidden>
                                <h6 id="pedidoIdh6"></h6>
                            </div>
                            <div class="mb-3">
                                <label for="fechaPedido" class="form-label">Fecha del pedido:</label>
                                <input id="fechaPedido" name="FechaPedido" hidden/>
                                <h6 id="fechaPedidoh6"></h6>
                            </div>
                            <div class="mb-3">
                                <label for="guiaInput" class="form-label">No. de guía:</label>
                                <input type="text" class="form-control" id="guiaInput" name="NoGuia">
                                <span id="errorGuia"></span>
                            </div>
                            <div class="mb-3">
                                <label for="paqueteriaSelect" class="form-label">Paquetería:</label>
                                <select class="form-select" id="paqueteriaSelect" name="Paqueteria">
                                    @foreach(var paqueteria in Model.ListaPaqueterias)
                                    {
                                        <option value="@paqueteria.NombrePaqueteria">@paqueteria.NombrePaqueteria</option>
                                    }
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="fechaEnvioInput" class="form-label">Fecha de envío:</label>
                                <input type="date" class="form-control" id="fechaEnvioInput" name="FechaEnvio">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-primary" onclick="validar()">Guardar cambios</button>
                            </div>
                        </form>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</main>

<script>
    function abrirModalEditar(btnEditar) {
        var pedidoId = btnEditar.getAttribute("data-id");
        var fechaPedido = btnEditar.getAttribute("data-fecha");
        var guia = btnEditar.getAttribute("data-guia");
        document.getElementById("pedidoId").value = pedidoId;
        document.getElementById("fechaPedido").value = fechaPedido;
        document.getElementById("guiaInput").value = guia;
        document.getElementById("pedidoIdh6").innerText = pedidoId;
        document.getElementById("fechaPedidoh6").innerText = fechaPedido;
    }
</script>

Views/Paqueteria/PedidosCompletados.cshtml
@model List<TodoParaTuPerro.Models.Pedidos>;

@{
    ViewData["Title"] = "PedidosCompletados";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="Pedidos">
                <i class="bi bi-grid"></i>
                <span>Pedidos sin enviar</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="PedidosEnviados">
                <i class="bi bi-grid"></i>
                <span>Pedidos enviados</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="PedidosCompletados">
                <i class="bi bi-grid"></i>
                <span>Pedidos completados</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="Paqueterias">
                <i class="bi bi-grid"></i>
                <span>Paqueterías</span>
            </a>
        </li>
    </ul>
</aside>
<main id="main" class="main">
    <div class="container">
        <h1 class="text-center mt-4">Pedidos completados</h1>
        <table class="table table-striped mt-4">
            <thead>
                <tr>
                    <th scope="col">No. de pedido</th>
                    <th scope="col">Fecha del pedido</th>
                    <th scope="col">No. de guía</th>
                    <th scope="col">Paquetería</th>
                    <th scope="col">Fecha de envío</th>
                    <th scope="col">Fecha de entrega</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pedido in Model)
                {
                    <tr>
                        <td>@pedido.IdPedido</td>
                        <td>@pedido.FechaPedido</td>
                        <td>@pedido.NoGuia</td>
                        <td>@pedido.Paqueteria</td>
                        <td>@pedido.FechaEnvio</td>
                        <td>@pedido.FechaEntrega</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</main>

Views/Paqueteria/PedidosEnviados.cshtml
@model List<TodoParaTuPerro.Models.Pedidos>;

@{
    ViewData["Title"] = "PedidosEnviados";
    Layout = "~/Views/Shared/_LayoutAdministrador.cshtml";
}

<aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="Pedidos">
                <i class="bi bi-grid"></i>
                <span>Pedidos sin enviar</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="PedidosEnviados">
                <i class="bi bi-grid"></i>
                <span>Pedidos enviados</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="PedidosCompletados">
                <i class="bi bi-grid"></i>
                <span>Pedidos completados</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Paqueteria" asp-action="Paqueterias">
                <i class="bi bi-grid"></i>
                <span>Paqueterías</span>
            </a>
        </li>
    </ul>
</aside>
<main id="main" class="main">
    <div class="container">
        <h1 class="text-center mt-4">Pedidos enviados</h1>
        <table class="table table-striped mt-4">
            <thead>
                <tr>
                    <th scope="col">No. de pedido</th>
                    <th scope="col">Fecha del pedido</th>
                    <th scope="col">No. de guía</th>
                    <th scope="col">Paquetería</th>
                    <th scope="col">Fecha de envío</th>
                    <th scope="col">Fecha de entrega</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pedido in Model)
                {
                    <tr>
                        <td>@pedido.IdPedido</td>
                        <td>@pedido.FechaPedido</td>
                        <td>@pedido.NoGuia</td>
                        <td>@pedido.Paqueteria</td>
                        <td>@pedido.FechaEnvio</td>
                        <td>@pedido.FechaEntrega</td>
                        <td>
                            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editarModal"
                                    data-id="@pedido.IdPedido" data-fecha="@pedido.FechaPedido" data-guia="@pedido.NoGuia"
                                    data-paqueteria="@pedido.Paqueteria" data-fechaEnvio="@pedido.FechaEnvio" onclick="abrirModalEditar(this)">
                                Editar
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <!-- Modal -->
        <div class="modal fade" id="editarModal" tabindex="-1" aria-labelledby="editarModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editarModalLabel">Editar Información</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" asp-action="ActualizarEntrega">
                            <div class="mb-3">
                                <label for="pedidoInput" class="form-label">No. de pedido:</label>
                                <h6 id="pedidoId"></h6>
                                <input id="pedidoIdInput" name="IdPedido" hidden>
                            </div>
                            <div class="mb-3">
                                <label for="fechaPedidoInput" class="form-label">Fecha del pedido:</label>
                                <h6 id="fechaPedido"></h6>
                                <input id="fechaPedidoInput" name="FechaPedido" hidden>
                            </div>
                            <div class="mb-3">
                                <label for="guiaInput" class="form-label">No. de guía:</label>
                                <h6 id="guia"></h6>
                                <input id="guiaInput" name="NoGuia" hidden>
                            </div>
                            <div class="mb-3">
                                <label for="paqueteriaSelect" class="form-label">Paquetería:</label>
                                <h6 id="paqueteria"></h6>
                                <input id="paqueteriaInput" name="Paqueteria" hidden>
                            </div>
                            <div class="mb-3">
                                <label for="fechaEnvioInput" class="form-label">Fecha de envío:</label>
                                <h6 id="fechaEnvio"></h6>
                                <input id="fechaEnvioInput" name="FechaEnvio" hidden>
                            </div>
                            <div class="mb-3">
                                <label for="fechaEntregaInput" class="form-label">Fecha de entrega:</label>
                                <input type="date" class="form-control" id="fechaEntregaInput" name="FechaEntrega">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-primary">Guardar cambios</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<script>
    function abrirModalEditar(btnEditar) {
        var pedidoId = btnEditar.getAttribute("data-id");
        var fechaPedido = btnEditar.getAttribute("data-fecha");
        var guia = btnEditar.getAttribute("data-guia");
        var paqueteria = btnEditar.getAttribute("data-paqueteria");
        var fechaEnvio = btnEditar.getAttribute("data-fechaEnvio");
        document.getElementById("pedidoId").innerText = pedidoId;
        document.getElementById("fechaPedido").innerText = fechaPedido;
        document.getElementById("guia").innerText = guia;
        document.getElementById("paqueteria").innerText = paqueteria;
        document.getElementById("fechaEnvio").innerText = fechaEnvio;

        document.getElementById("pedidoIdInput").value = pedidoId;
        document.getElementById("fechaPedidoInput").value = fechaPedido;
        document.getElementById("guiaInput").value = guia;
        document.getElementById("paqueteriaInput").value = paqueteria;
        document.getElementById("fechaEnvioInput").value = fechaEnvio;
    }
</script>